core/state/state_object.go
core/state/statedb.go

cherry-picked from https://github.com/ethereum/go-ethereum/pull/3006/commits/62f86a7479f0c81f2f4baab69980ffc7625aeb5a
testing resync now

core/state: Fix memory expansion bug by not copying clean objects

---

README.md

The builds are polling from Github on *master* and *develop*, once every 20 minutes.  Tests are being skipped at the moment.  Artifacts are being uploaded to [BinTray](https://bintray.com/ethereumproject/GoEthereumClassic/go-ethereuml).
Release tags are not being automatically built yet, that is in progress.

Update README with new build status icons

---

cmd/utils/flags.go
core/config.go
core/fork.go

Fix #51
Updates existing chain config with new Diehard fork (if not configured). Also this config was split into two, which was semantically incorrect and resulting into double messaging in console log.
Fork info was improved somewhat, now it looks like this:
```
$./build/bin/geth --datadir /tmp/gethtest1
I1007 21:43:42.389565 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /tmp/gethtest1/chaindata
I1007 21:43:42.400629 cmd/utils/flags.go:846] --------------------------------------------------------------------------------------------------------------
I1007 21:43:42.400655 cmd/utils/flags.go:847] Loading blockchain: genesis block "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3".
I1007 21:43:42.400668 cmd/utils/flags.go:848] 3 blockchain hard-forks …
```

Ecip-1010 config

---

build/ci.go
build/deb.rules

some changes to support uploads to our new PPA archive on Launchpad.  I have already built 1 Ubuntu release of the *develop* branch manually this way, found [here](https://launchpad.net/~ethereum-classic/+archive/ubuntu/etc-geth)

modify ci script to support TeamCity and etc build

---

cmd/utils/flags.go

fix #62
```
I1017 15:10:43.639159 cmd/utils/flags.go:853] --------------------------------------------------------------------------------------------------------------
I1017 15:10:43.639185 cmd/utils/flags.go:854] Starting Geth Classic 3.0.0-stable-d76ad4eb
I1017 15:10:43.639194 cmd/utils/flags.go:855] Loading blockchain: genesis block "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3".
I1017 15:10:43.639211 cmd/utils/flags.go:856] 4 blockchain hard-forks associated with this genesis block:
I1017 15:10:43.639231 cmd/utils/flags.go:872]  Homestead hard-fork at block 1150000
I1017 15:10:43.639250 cmd/utils/flags.go:872]  ETF hard-fork at block 1920000 resulted in a network split (support: false)
I1017 15:10:43.639263 cmd/utils/flags.go:872]  GasReprice hard-fork at block …
```

Show Geth version during startup

---

build/ci.go
build/deb.control
build/deb.rules

go 1.7 is not available on some of our ubuntu distro targets, preventing the PPA from building the package.  Only 16.10 has go-1.7.

roll back to go-1.6 for building on launchpad

---

build/ci.go

the purpose is to prevent attempting to build and do a PPA upload for tags belonging to upstream.  SemVer makes distinguishing our tags from theirs much easier.

adapt upload filter to semver

---

eth/api.go

According to specification https://github.com/ethereumproject/wiki/wiki/JSON-RPC#eth_getblockbyhash
json response with block must contains "receiptsRoot" field.
Ethereum already fixed it in https://github.com/ethereum/go-ethereum/pull/3088/commits/71e8ae01b84cdde56761436a52552a25b03d2a97

JSON-RPC: Block field receiptRoot renamed to receiptsRoot

---

eth/backend.go

@splix Re-submitting (clean) PR, #113 may be closed in substitution of this one. 
Tested on Ubuntu 16.04:
Mainnet:
I1228 10:38:41.707743 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1, **Chain Id: 61**
Testnet:
I1228 10:40:16.704581 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 2, **Chain Id: 62**

eth: Show Chain Id in startup logs. Resolves #110

---

cmd/geth/main.go

I initially thought it was a bug when I saw `unknown` as the logged Geth version. There might be a better wording than my suggested "source"... open to improvements.

Use Version = "source" for non-release builds

---

accounts/cache_test.go

problem: TravisCI test _accounts/cache_test.go_: `TestWatchNoDir()` fails for macOS (#194)
possible solution: increase sleep and more verbose logging
other problem: can't recreate locally so I'll be keeping an eye on this CI

test: accounts watch file TravisCI for macOS

---

eth/downloader/downloader.go

It is annoying and misleading. Blame @sjmackenzie for the good idea.  😉 👍

Remove 'sync busy' from standard logging

---

cmd/geth/chaincmd.go
cmd/geth/chainconfig.bats
cmd/geth/cli.bats
cmd/geth/flag.go
cmd/geth/flag_test.go
cmd/geth/flagdir.go
cmd/geth/flags.go
cmd/geth/genesis.bats
cmd/geth/main.go
cmd/geth/usage.go

Moves `--lowercasecommand` to `--lower-case-command`.
Retains original commands as "aliases" for backwards compatibility. 
Resolves #198.

Use --lower-case-concatenated commands

---

eth/api.go

For some cases, a third party (eg. SmartPool) might want to get block header corresponding to last "pow-work" (returned by `eth_getWork`). The only potential way is using `eth_getBlockByNumber` with pending and recalculate the pow hash to see if it matches the hash returned from `eth_getWork`. Unfortunately, `eth_getBlockByNumber` always returns null for `logsBloom`, one field that is used to calculate `HashNoNonce`, so it is currently impossible to do so.
Right now, I don't really understand the reason behind setting logsBloom to null for pending block when it is useful to have logsBloom returned as I described above.
Note: This PR was also merged with EF's go-ethereum repository.

do not clear logsBloom field with pending block

---

README.md
cmd/geth/flag.go
core/config.go
core/config_test.go
eth/backend.go

Also rearranges startup logging to dedupe genesis hash logs and updates README to reflect revised `--testnet` vs `--chain` usage.
Fixes #229

Fix chain config parsing interface{} bug

---

README.md
cmd/geth/flag.go
cmd/geth/migrate_datadir.bats

`--chain=custom`, `--data-dir`, and `--chain-config` _skip_ migrating from old schema to new.
`--chain=mainnet|morden|testnet` will allow the migration, checking old `testnet` dir for relevant data if currently enabling test mode.
Improves check for ETC-relevant chaindata uses blockchain height from DB and, if sufficiently high (>=1920000), checks for HF required block hash.

Refactor data migration to make simpler and more thorough

---

eth/downloader/downloader.go

The signature for Downloader.cancel is
```go
func (d *Downloader) cancel()
```
yet the comment claims it returns true if the cancel operation
was completed.
Just a minor oversight, traceable back to commit
https://github.com/ethereumproject/go-ethereum/commit/fc7abd98865f3bdc6cc36258026db98a649cd577#diff-c2fa15e758e986688c646459d8970a50L310
in which the signature was changed but the comment wasn't.

eth/downloader: conform Downloader.cancel comments to its signature

---

cmd/geth/flags.go
cmd/geth/main.go
logger/glog/glog_file.go

Creates flag for existing functionality provided by `glog` logger. 
If flag is set and value not specified, the default is `<EthereumClassic>/logs`.
If directory value for enabled flag is not yet existing, it will be created.
Geth by defaults logs to `stderr`, making required redirection `2>`, which is atypical. I don't know why it does that but there's probably a good reason. This functionality is unchanged.
This one's for you, @r8d8.

create '--log-dir' flag to specify directory for logging

---

CHANGELOG.md
README.md
cmd/geth/chainconfig.bats
cmd/geth/cli.bats
cmd/geth/flag.go
cmd/geth/flag_test.go
cmd/geth/flags.go
cmd/geth/genesis.bats
cmd/geth/main.go
cmd/geth/migrate_datadir.bats
cmd/geth/migrate_datadir.go
cmd/geth/usage.go
core/config.go

Unifies `--chain` flag to behave equivalently for custom and default networks, replacing `--chain-config` option.
- replace --chain-config with improved --chain behavior,
where --chain checks expected path (/customnet/chain.json)
for custom external JSON config in case of unknown argument,
where known arguments are: [mainnet, morden, testnet]
- update tests to reflect new usage
- significantly refactor cmd/geth/flag.go to be simpler
- ensure `dump-chain-config` command is only used for defaults

Chain identity

---

CHANGELOG.md
README.md
cmd/geth/boot.go
cmd/geth/consolecmd.go
cmd/geth/monitorcmd.go
cmd/gethrpctest/main.go
node/config.go

... by default.
Created `geth.ipc` already lives in `/mainnet/`, so `attach` should look in `/mainnet/geth.ipc`, likewise for `--chain=morden|CUSTOM`. Command still accepts `ipc:path/to/geth.ipc` as an optional argument.
Also updates CHANGELOG and README with typos/corrections.

`attach` command should use chain directory schema

---

eth/api.go

Even when an account has zero balance, nonce and no code, it might
still be considered existing due to CALL/CALLCODE/message call
transactions with zero value transfer, or CREATE/contract creation
transactions with no code deposit and zero value transfer.
Whether an account exists affects the gas cost. So this at least
affects EVM projects like SputnikVM who wants to run regression tests
using JSON-RPC.
See https://github.com/ethereumproject/sputnikvm/issues/206 for a related bug.

api: add debug_AccountExist that checks whether an account exists

---

core/state/statedb.go

solution: use mutex locks for getStateObject and setStateObject
This is an initial hotfix for #284 (see below).
----
Note: StateDB uses stateObjects and stateObjectsDirty as maps,
apparently without any locks for granular actions (only statedb New, Reset, copy)
This seems like a red flag to me.
... ETHF also doesn't use granular locks for these map r/w's.
TODO: research this more.

fix: concurrent map r/w for stateobject

---

.travis.yml
appveyor.yml
travis-deploy.sh

solution: use go build to provide deploy script executables for all os's.
There may be another (possibly related?) issue with appveyor not being able to
find the file to upload -- because of not-interpolating env vars in filename?

problem: CI: go get -u exits 1 on already-to-date

---

appveyor.yml

either because of wrong gcloud-appveyor.json.enc file or because openssl cli not available
solution: install and use secure-file tool to decrypt prior to uploading

problem: appveyor fails to deploy

---

p2p/discover/database.go

This is a very common 'error' occurring when a given node is as-of-yet unknown,
and does not necessarily reflect an invalid or otherwise problematic node.
Fixes #308
Changes from 
```
failed to retrieve node
```
to: 
```
node does not exist in database:
```
This happens in the context of p2p node parsing:
```
I0720 15:32:30.343582 p2p/discover/table.go:471] Bonding 8c327816cc9e8f20: known=false, fails=0 age=416828h32m30.34357842s
I0720 15:32:30.343835 p2p/discover/database.go:183] failed to retrieve node 2e20b28392171e5b5bdcacca73a9c0a68c1bf20bfb4b84f1e0b47a061c3cedba1aa57e8ecca5e5e6ef9b24d65c664f53e00c910cf0cad59af3021c08def002b7: leveldb: not found
```
If you've got other suggestions for wording, they would be happily considered...

Fix: logging  not-found node is misleading

---

eth/handler.go

Discussion at #309.
After sending a request to check for a particular hash of a hard fork block, allow the peer to claim that it does not know about this block, and then assume the peer is valid, unless it shows it's not so.

p2p: good will assumption for the DAO fork

---

CHANGELOG.md
eth/api.go

Creates `TraceTransaction` method for public debug API.
Rel #294

eth/api: implement debug_traceTransaction

---

README.md
cmd/geth/chainconfig.bats
cmd/geth/flag.go
core/config.go
core/config_test.go

Rel #330 
This is a solution that doesn't alter the behavior or enforce limitations on the `--chain` argument (either `path/to/config/file[.json]` naming or `chain-identity`), but errors and exits if it finds an invalid config file at `path/to/config/file` or `[./]chain-identity`. 
The only edge case this leaves open is if there's a _file_ `chain-identity` in the CWD which is not intended to be used as a configuration file, then it will error. But in this case I think the error will be descriptive enough to allow the user to workaround it.

cmd/geth:fix: invalid external chain config error is hidden

---

CHANGELOG.md
eth/api.go
internal/web3ext/web3ext.go

Rel #335 
I chose to return the number in hexadecimal format because that's consistent with the other `eth_` call returning a *big.Int `eth_gasPrice`. I'm not set on this; it may be better to return as a plain int since there's no need for _big_ness. Another option would be to return as a string, akin to `net_version`, which returns `"1"` and `"2"`. 
In case no chain id is configured, it will return 0.
Finally, it may be useful to also include the fork number at which EIP155 is implemented for the given configuration; Morden -> 1915000, Mainnet -> 3000000, custom/private -> _n_
Eg: 
Current proposed:
```json 
{
"jsonrpc": "2.0",
"id": 1,
"result": "0x3d"
}
```
or possibly with fork number:
```json
{
"jsonrpc": "2.0",
"id": 1,
"result": {
"chainId": "0x3d",
"blockNumber": "0x2dc6c0"
}
} …
```

implement 'eth_chainId' JSON-RPC method

---

cmd/geth/consolecmd.go
cmd/geth/main.go

Current use:
```shell
$ geth --exec 'console.log("hello");' console
```
Proposed changes allow alternate use:
```shell
$ geth console --exec 'console.log("hello");'
```
This applies for both commands `console` and `attach`.
In case of invalid use, show usage as below and exit `1`.
```shell
$ geth --exec 'console.log("hello");'
2017/10/09 09:24:45 Error: --exec flag requires use of 'attach' OR 'console' command, command was: ''
console [command options] [arguments...]
The Geth console is an interactive shell for the JavaScript runtime environment
which exposes a node admin interface as well as the Ðapp JavaScript API.
See https://github.com/ethereum/go-ethereum/wiki/Javascipt-Console
OPTIONS:
--exec value	Execute JavaScript statement (only in combination with console/attach)
attach …
```

cmd/geth: allow --exec flag as global or command flag

---

miner/mlog.go
miner/worker.go

Will update https://github.com/ethereumproject/go-ethereum/wiki/mlog-API#lines-reference with `MINER.WORK.BLOCK_NUMBER` -> `MINER.UNCLE.BLOCK_NUMBER` signature as well.

Fix panic nil pointer miner mlog

---

eth/api.go
internal/jsre/ethereum_js.go
internal/web3ext/web3ext.go

Methods currently exist in web3ext.js, but were unimplemented in API. 
- `debug.verbosity(n)`, where `n` is a uint corresponding to established log levels `1...6,100` (`Error...Detail, Ridiculousness`).
Returns int, eg. `5`, upon successful setting, and error `invalid verbosity value` on fail. Using `debug.verbosity()` (where `n` is nil) caused method to acts a getter function, and returns current value. See `--verbosity` flag for usage context.
```
> debug.verbosity();
3
> debug.verbosity(4);
4
> debug.verbosity(1);
1
```
- `debug.vmodule(s)`, where `s` is a comma-separated `k=v` string, eg. `eth*=3,miner=4,core/blockchain=5`. Returns regex-compiled string matching set input. See `--vmodule` flag for usage context. Like above, an empty parameter (`s = 0`) causes the method to act as a …

implement debug logging/verbosity api methods

---

cmd/geth/flags.go

mlogs are data rich, and if geth is run constantly and often, will require a significant
amount of storage, eg. ~500M for an 8hr sync.
I don't think most users will require mlogs, so let's save them some space.
For users wanting to enable mlogs for log analysis, they can still (of course)
opt-in with '--mlog=[kv|json|plain]'.
Default 'off' setting is also congruent to normal FS logging, which is by default off,
but can be enabled with '--log-dir'.

Set mlog default to 'off'

---

eth/sync.go

This issue was recorded when `no space left on device`.
solution: check for invalid stored TD during sync and exit 1 with error message
Investigating and developing further possible involvement of invalid stored `TD` rel #274 as well.

Fix nil pointer when chaindb currentblock has no TD

---

cmd/geth/chaincmd.go
cmd/geth/cmd.bats
cmd/geth/cmd.go
cmd/geth/main.go

`rm -rf` chaindata. This is a nuclear (drastic) command.
Basic use:
```
$ geth reset
```
```
$ geth --data-dir="./somewhere" --chain="morden" reset
```
Example:
```shell
~/Library/EthereumClassic  ⟠ geth reset --help
reset [arguments...]
Reset does a hard reset of the entire chain database.
This is a drastic and irreversible command, and should be used with caution.
The command will require user confirmation before any action is taken.
~/Library/EthereumClassic  ⟠ geth --chain mainnet-corrupted15 reset
This will remove the directory='/Users/ia/Library/EthereumClassic/mainnet-corrupted15/chaindata' and all of it's contents.
** Are you sure you want to remove ALL chain data? [y/n]: asd
* INVALID RESPONSE: Please respond with [y|yes] or [n|no], or use CTRL-C to abort.
This will remove the …
```

feature: reset command

---

cmd/geth/account.bats
cmd/geth/accountcmd.go
cmd/geth/accountdb.bats
cmd/geth/apicmd.go
cmd/geth/chaincmd.go
cmd/geth/cmd.go
cmd/geth/consolecmd.go
cmd/geth/main.go
cmd/geth/monitorcmd.go
cmd/geth/usage.go

standardize help usage text at 1-tab indent... as well as
- write `api` command output to stderr
- fix account command '--help' and usage behavior ⬇️ 
`$ geth account` used to list accounts (which should be the job of `geth account list`) and `geth account --help` used to show entire global app help usage. Now `geth account [|--help]` shows just relevant account usage info

improve CLI usage formatting

---

core/blockchain.go
core/headerchain.go

One of the checks that gets run as a part of blockchain stability/recoverability is to see if there's any block data _beyond_ the current apparent stored `head` block. And `blockchain.Recover()` begins at `1` and moves forward incrementally until it finds an invalid block. If it finds an invalid block at `100`, it will recover to block `99` and set the new head there. However, since `blockchain.SetHead(99)` only purges blocks _between_ the new head and the old head (eg. `99` and `100`), there will still exist block data for `101`. Because of this, `blockchain.LoadLastState` will find block `101` (again) and restart the recovery process.
While an invalid block in the _middle_ of the blockchain is very rare and probably only exists for data that's been corrupted on purpose (normally it will …

avoid recovery deadlock/loop given invalid block in middle of stored blockchain data

---

cmd/geth/chainconfig.bats
cmd/geth/flag.go

solution: remove them, both as *nix (`/`) and windows separators (`\`)
fixes #391

fix trailing slashes from --chain=value/

---

.travis.yml
appveyor.yml

The CIs are currently set to deploy only when `branch=master`. Both Travis and Appveyor consider tags as branches for their environment settings. So building from a tagged commit yields `branch=4.1.2`, which is not considered deployable.
The current solution for this is to restart the `branch=master` builds once the tag has been pushed, or to merge locally, tag, push tag, then finally push merge. Both are rather annoying and seem kind of backwards.
- travis: add identical deployment providers with different conditions (see link)
- appveyor: use ps deployment conditional to check for `APPVEYOR_REPO_BRANCH<string>=master` OR `APPVEYOR_REPO_TAG<string?>`
Noting:
https://github.com/travis-ci/travis-ci/issues/7780#issuecomment-302389370

CI: deploy on tags as well as master

---

logger/glog/glog.go
logger/glog/glog_test.go

problem: when rotation of old files take a long time (compression is
turned on, there are lots of large old files to rotate, etc) and there
is new rotation request (current log file size or time based) it is
possible, that rotateOld will be executed twice in parallel, and list
of files gathered in one execution can be outdated by changes made by
another execution.
comment: log handling is very conservative to avoid any loss of logs.
If there is a problem with opening a file (for example for compression),
fatal error is reported.
Following KISS principle, mutex is added to protect the entire rotateOld.

make rotateOld thread safe

---

cmd/geth/main.go

geth always uses `runtime.GOMAXPROCS(runtime.NumCPU())` which doesn't allow user to override `GOMAXPROCS` value with environment variable.
only set runtime.GOMAXPROCS if GOMAXPROCS env var is not set
This allows user to override go max procs config with `env GOMAXPROCS=n geth [...]` instead of geth demanding to use number of available CPUs on machine.

allow GOMAXPROCS to be set with env var

---

logger/glog/glog.go

Small change to improve durability of logging.

Ensure that gzipped log file is fsync'ed before removing plain log

---

appveyor.yml

just taken verbatim from https://github.com/rust-lang-nursery/rustup.rs/issues/1316#issuecomment-354156348
we can revert this change once the rustup issue has been resolved. but for now a requirement for us to be able to get builds to pass so we can merge stuff.

downgrade rustup to nonbroken version for appveyor

---

logger/glog/glog.go

solution: remove log compression from `rotateCurrent` function, latest
file will be compressed anyways during normal run of `ratateOld`
function. This removes race condition (two goroutines trying to compress
same file) and eliminates the problem that logs are suspended for time
necessary to compress large file (may took many seconds)

problem: synchronous log compression

---

appveyor.yml

This reverts commit d6323ae50401867c8086216e1af018a8df3e5d96.
> Checking claim is fixed: https://github.com/rust-lang-nursery/rustup.rs/issues/1316#issuecomment-355304592

Revert "problem: rustup broken"

---

cmd/geth/log_dispatch.go
cmd/geth/log_display_basic.go
cmd/geth/log_display_util.go

`lsMode` is not guaranteed to be thread safe. If functions want to assure this, they can use a lock or assign a separate variable.
```
2018-01-29 01:51:18 Fast #1591550 of #5290128 30.09% 253/63 blk/mgas sec 6/25 peers
2018-01-29 01:56:09 Discover 5/25 peers
panic: unreachable
goroutine 119 [running]:
main.glob..func5(0xc421410fc0, 0xdf8475800, 0x0, 0x19, 0x0)
/home/travis/gopath/src/github.com/ethereumproject/go-ethereum/cmd/geth/log_display_basic.go:255 +0x1174
main.glob..func4(0xc4200d5cc0, 0xc421410fc0, 0x0, 0x0, 0xdf8475800)
/home/travis/gopath/src/github.com/ethereumproject/go-ethereum/cmd/geth/log_display_basic.go:89 +0xaf
main.(*displayEventHandlers).runAllIfAny(0xc42068e180, 0xc4200d5cc0, 0xc421410fc0, 0x0, 0x0, 0xdf8475800, 0x7) …
```

log mode not locked, should not panic if default

---

.travis.yml

As CircleCI builds are (success)fully running now, we can disable OS X builds on TravisCI.

Disable Mac OS X builds on TravisCI

---

appveyor.yml

Appveyor out of artifact storage, and impossible to delete any of the old artifacts.
```
ok  	github.com/ethereumproject/go-ethereum/rpc	1.116s
ok  	github.com/ethereumproject/go-ethereum/tests	20.755s
ok  	github.com/ethereumproject/go-ethereum/trie	0.953s
ok  	github.com/ethereumproject/go-ethereum/whisper	9.888s
go build -tags=sputnikvm -ldflags "-X main.Version=%VERSION%" ./cmd/geth
7z a geth-classic-win64-%VERSION%.zip geth.exe
7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04
Scanning the drive:
1 file, 38813643 bytes (38 MiB)
Creating archive: geth-classic-win64-v4.2.2+8-393532e.zip
Items to compress: 1
Files read from disk: 1
Archive size: 11499864 bytes (11 MiB)
Everything is Ok
Discovering tests...OK
Collecting artifacts...
Found artifact …
```

remove appveyor artifact storage

---

.circleci/config.yml

```
==> Downloading https://homebrew.bintray.com/bottles/go-1.9.4.sierra.bottle.tar.gz
==> Pouring go-1.9.4.sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/go
Target /usr/local/bin/go
is a symlink belonging to go. You can unlink it:
brew unlink go
To force the link and overwrite all conflicting files:
brew link --overwrite go
To list all files that would be deleted:
brew link --overwrite --dry-run go
Possible conflicting files are:
/usr/local/bin/go -> /usr/local/Cellar/go/1.9.3/bin/go
/usr/local/bin/godoc -> /usr/local/Cellar/go/1.9.3/bin/godoc
/usr/local/bin/gofmt -> /usr/local/Cellar/go/1.9.3/bin/gofmt
==> Caveats
A valid GOPATH is required to use the `go get` command.
If …
```

CircleCI: specify go1.9.3, and only (brew) install if not cached

---

cmd/geth/log_display_dash.go
eth/backend.go

Added chain name, id(morden or mainnet), chain id and p2p rx/tx rates/totals to the dash display.
I have attached screenshot for the same below.
Signed-off-by: Manush <manush@lavellenetworks.com>

Added chain configuration and p2p rates/totals to dash display

---

tests/block_test.go

Because of anti-selfish-miner code which is randomized, this test case
was not deterministic. Explicit seeding of random number generator makes
the test deterministic (however not all code-branches are tested).

solution: make TestBcForkUncleTests deterministic

---

eth/api.go
internal/jsre/ethereum_js.go

Rel #512
https://github.com/ethereumproject/wiki/wiki/JSON-RPC#eth_sign
https://wiki.parity.io/JSONRPC-eth-module#eth_sign
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sign
https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal_sign

problem: eth_sign should accept variable data param

---

eth/handler.go

solution: check if downloader is available before
since the sync method is synchronous

problem: calling synchronise from handler more than necessary

---

p2p/discover/table.go
p2p/discover/table_test.go

Please merge after #523.
This implements countermeasure 3 in
https://www.cs.bu.edu/~goldbe/projects/eclipseEth.pdf by changing
bucket choosing from logdist(self.nodeID, n) to logdist(s1, sha3(n,
s2)) where s1, s2 are random private hash (32 bytearray).

 p2p: use logdist(s1, sha3(n, s2)) for bucket choosing 

---

logger/mlog_file.go

solution: reorder to keep descending priority/scope
See the `session` (`ksJR`) vals in Key Value and Plain for only changes
----
__Key value__:
```
2018/03/13 22:40:35 [miner] session=ksJR REMOTE_AGENT SUBMIT WORK work.nonce=$INT work.mix_digest=$STRING work.hash=$STRING work.exists=$BOOL
```
__JSON__:
```json
{"component":"miner","event":"remote_agent.submit.work","session":"ksJR","ts":"2018-03-13T22:40:35.211296749+09:00","work.exists":true,"work.hash":"string","work.mix_digest":"string","work.nonce":0}
```
__Plain__:
```
2018/03/13 22:40:35 [miner] ksJR REMOTE_AGENT SUBMIT WORK $INT $STRING $STRING $BOOL
```
----
⬇️ 
----
__Key value__:
```
2018/03/13 22:40:35 [miner] REMOTE_AGENT SUBMIT WORK session=ksJR work.nonce=$INT work.mix_digest=$STRING work.hash=$STRING work.exists=$BOOL
``` …

problem: mlog session id vals out of order in line

---

eth/mlog.go
eth/mlog_test.go

fixes #541 
problem: mlog delegate is unable to cast a data value because it is invalid - _because_ there was an error in the wire protocol. 
solution: all mlog wire delegate should check for incoming errors before `fatal`ing on casting errors; if there's an incoming error it should not be guaranteed that data values are valid.

fix mlog wire casting cases with error

---

cmd/geth/cmd.go
cmd/geth/flag.go
cmd/geth/flag_test.go
cmd/geth/log_display_dash.go
cmd/geth/migrate_datadir.go
core/config.go
core/config_test.go
eth/downloader/downloader.go
eth/handler.go
eth/handler_test.go

- move SufficientChainConfig and ChainIdentity vals from `cmd/geth` to `core` package and make accessible via getter/setter fns
- implement `core.GetLatestRequiredHashFork` fn to handle configs with multiple forks with `requiredHash`s. 
+ [ ] One idea around this would be to shift `requiredHash` configuration out of the `Fork` config and toward a simple `blockNumber: hash` key-val configuration, although would introduce complexity because of backwwards-compatibility requirements. Probably not worth it, and there are benefits to the additional configuration options provided by Fork syntax, and to reduce "checkpoint" multiplicity, a single "last-relevant" checkpoint could be used.
- fix `requiredHash` check for newly-registered `eth/*peers` (in eth/handler.go). See #559. Please give …

chain config globals -> core/, fix requiredHash check and extensibility

---

eth/api.go

The endpoint is documented and is just simply missing.
- https://github.com/ethereumproject/go-ethereum/wiki/JavaScript-Console#debugsethead
- https://github.com/ethereum/go-ethereum/wiki/Management-APIs#debug_sethead

implement missing debug_setHead api method

---

rpc/server.go

problem: EOF error interrupts pending requests
solution: cherry-pick @karalabe's 1018bf6a00be475cb9af2812c1f61fa8530068a3
> https://github.com/ethereum/go-ethereum/pull/3814
Fixes #577

rpc: honour pending requests before tearing conn down

---

crypto/crypto_test.go
crypto/secp256k1/secp256.go
crypto/secp256k1/secp256_test.go

problem: nondeterministic K-value in ECDSA algo (crypto.Sign)
solution: move to a deterministic k-value using RFC6979
rel https://github.com/ethereum/go-ethereum/issues/2190
rel https://github.com/ethereum/go-ethereum/pull/3561
rel #245 
----
Before this change `eth_sign`, for example, would generate nondeterministic signatures, for example:
```
> var acc=eth.accounts[0];
undefined
> acc
"0x3d1cf2f13db48a49bc07ae7018826b6ea2ede093"
> personal.unlockAccount(acc);
Unlock account 0x3d1cf2f13db48a49bc07ae7018826b6ea2ede093
Passphrase:
true
> eth.sign(acc, "0xdeadbeef");
"0x527a0019b5ce8a99f7be59f2ec78b206f820699ff1b9f31b1cdc6fda781028272108210671dc6436eea267fb39cbb4c5e7e6a3d572f789417a693aeec14f2e0b1c"
> eth.sign(acc, "0xdeadbeef");
"0x38450e81a02f388a2c903453e4c5bee80da9eb134cc030a2cf515aff0f …
```

use deterministic K-value in ECDSA signing algorithm

---

crypto/crypto_test.go
eth/api.go
internal/web3ext/web3ext.go

Exposes existing `crypto.EcRecover` method to `personal` API module. 
See https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal_ecrecover for matching EF method.
For example:
```
> personal.sign("0xdeadbeef", eth.accounts[0], "foo");
"0x33a614e8cbf323cb705711a1c43c9a8522b11bc07f22d8425e73aec2075d331408d2ce4df925e29e87dae8bc6c79bfe3baeb185f75d9fc1b60e1acb5f8122e171c"
> personal.ecRecover("0xdeadbeef", "0x33a614e8cbf323cb705711a1c43c9a8522b11bc07f22d8425e73aec2075d331408d2ce4df925e29e87dae8bc6c79bfe3baeb185f75d9fc1b60e1acb5f8122e171c");
"0x3d1cf2f13db48a49bc07ae7018826b6ea2ede093"
> eth.accounts[0];
"0x3d1cf2f13db48a49bc07ae7018826b6ea2ede093"
```
Depends on #565

implement personal_ecRecover API method

---

logger/glog/glog_test.go

solution: ensure, that log rotation is executed (by forcing atomic guard variable to desired value before the testing)
This hopefully fixes #564.

Make glog tests deterministic

---

cmd/geth/flags.go

IMO default 128mb is pretty tiny, and leads to defaultily slow syncing.
Moving to 1024mb default is on par with gethETC, though Parity appears to still use 128mb as of 1.9.7.

bump db cache default val from 128 -> 1024mb

---

common/compiler/solidity.go

was removed in 0.4.21
> https://github.com/ethereum/solidity/issues/3695
> https://github.com/ethereum/go-ethereum/pull/16289/files
Rel #583
solution: remove flag option

problem: solidity --add-std deprecated

---

core/multivm_processor.go

Fixes 
```
panic: runtime error: invalid memory address or nil pointer dereference                                   
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaa0fa7]                                    
goroutine 188627 [running]:                          
sync/atomic.(*Value).Load(...)                       
/home/tomek/go/src/github.com/ethereumproject/go-ethereum/core/types/block.go:398                 
github.com/ethereumproject/go-ethereum/core/types.(*Block).Hash(0x0, 0x0, 0x0, 0x0, 0x0)                  
/home/tomek/go/src/github.com/ethereumproject/go-ethereum/core/types/block.go:398 +0x67           
github.com/ethereumproject/go-ethereum/core.ApplyMultiVmTransaction(0xc420427b90, 0xc421808360, 0xc43418aaa0, 0xc42bec9700, 0xc42b1b98c0, 0xc42a789400, …
```

multivm/sputnikvm.RequireBlockhash: ensure block exists in db

---

Makefile
README.md

Instructions were previously verbose, and have been exposed as `make` commands in the Makefile.
Fixes and improves a few surrounding typos and stylistics.

update README build/+install instructions to use Make commands

---

core/blockchain.go
core/database_util.go
eth/api.go
internal/web3ext/web3ext.go

- refactor (rename variable) `blockchain.useAddTxIndex` -> `blockchain.useAddrTxIndex` (bd8f884)
- set atxi progress bookmark when `buildAtxi` is either not in use or has reached stop point (2fcbf7c)
- add alias `geth_getTransactionsByAddress` for existing `geth_getAddressTransactions` (#594)
- (02a6ceb) when `geth_getATXIBuildStatus` is called without `geth_buildATXI` having been invoked, return `"result": null` instead of 
```
{
"jsonrpc": "2.0",
"id": 1,
"result": {
"Start": 18446744073709551615,
"Stop": 18446744073709551615,
"Current": 18446744073709551615
}
}
```

review and proposed modifications for extended atxi api PR #598

---

cmd/geth/flag.go
cmd/geth/log_context.go
p2p/discover/udp.go

Yields:
```
$ geth --chain morden --unlock 0 --rpc
2018-05-21 13:55:27 Geth Classic version: whilei.v5.3.0+2-b4b0c9f[branch=feat/unlock-rpc-warn,commit=problem:-unsafe-usage-is-accompanied-with-a-usage-warning,built=May/21Mon-13:55:19]
2018-05-21 13:55:27 Blockchain: Morden Testnet
2018-05-21 13:55:27 Chain database: /Users/ia/Library/EthereumClassic/morden/chaindata
2018-05-21 13:55:27 Blockchain upgrades configured: 6
2018-05-21 13:55:27   494000 Homestead
2018-05-21 13:55:27  1783000 GasReprice
2018-05-21 13:55:27  1885000 The DAO Hard Fork
2018-05-21 13:55:27  1915000 Diehard
2018-05-21 13:55:27  2000000 Gotham
2018-05-21 13:55:27  2300000 Defuse Difficulty Bomb
2018-05-21 13:55:27 --------------------------------------------------------------------------------------------------------- …
```

log warning if unsafe use of RPC and account unlocking

---

core/state/statedb.go

solution: use mutex lock
fixes #284, again

problem: concurrent rw on state db stateobjects map

---

.circleci/config.yml
appveyor.yml

Forked versions of this repo failed CI tests because deploy steps requiring keys and uploads would fail.
Add conditionals to CI configs specifying that deploy should only happen from this main repo.

CI: attempt deploy steps only from main repo

---

common/version.go
logger/glog/glog.go

Since version, context, and session data is available from `common`, let's use it in debug log files to provide additional context for interpreting debug logs.
Changes this:
```
Log file created at: 2018/05/28 22:06:40
Running on machine: node-geth-500-k969c
Binary: Built with gc go1.9.4 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
```
To this:
```
Log file created at: 2018/05/29 07:15:11
Binary: Built with gc go1.9.2 for darwin/amd64
Context: VERSION=whilei.v5.3.0+22-58cea72[branch=feat/debug-log-with-version-header,commit=problem:-debug-log-files-lack-available-context-info,built=May/29Tue-07:14:48] GO=go1.9.2 GOOS=darwin GOARCH=amd64 SESSIONID=CAUt HOSTNAME=mh USER=ia MACHINE=a2c2f59f PID=18704
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid …
```

add available context info to debug log file headers

---

p2p/nat/nat.go

Rel #587 
- https://github.com/ethereum/go-ethereum/issues/2380#issuecomment-260311264
- https://github.com/ethereum/go-ethereum/issues/890#issuecomment-100552407

relegate UPnP mapping logs to info and debug

---

cmd/geth/build_atxi_cmd.go
core/atxi.go
core/blockchain_test.go
core/database_util_test.go
eth/api.go

problem: atxi pagination param can cause slice OoB
solution: ensure param within len lim
Fixes #626

fix atxi pagination OoB possibility

---

.circleci/config.yml
appveyor.yml
cmd/geth/main.go
core/blockchain_test.go
core/multivm_fake_processor.go
core/multivm_processor.go
core/state_processor.go
tests/init.go

This enables running tests and any other go commands outside of application CLI usage with or without(default) SputnikVM instead of the native geth VM.
@mersinvald, your review encouraged too. (Don't know why can't request official for you... maybe you still need to be added to ethereumproject/?)

make sputnikvm enable-able via go link

---

scripts/build_sputnikvm.sh

solution: check for existence of 'cargo' command, and if it DOESNT exist
then prompt user to go ahead with rustup installation, otherwise just
exit

problem: make install/build command fails if rust/cargo not installed

---

core/blockchain.go
core/tx_pool.go
eth/api.go
eth/downloader/downloader.go
eth/handler.go

This fixes some log-line formatting directive linter warnings that showed up in [an Appveyor build](https://ci.appveyor.com/project/splix/go-ethereum/build/1.0.2174) for some reason.

fix linter warnings

---

cmd/geth/flag.go

simply fix a couple formatting directives
The warnings cause the appveyor build to fail, as seen here: https://ci.appveyor.com/project/splix/go-ethereum/build/1.0.2181.

fix linter warnings from appveyor 

---

eth/api.go

solution: include them
Fixes #684 
Yields:
__js console__:
```js
> t = eth.getTransaction(eth.getBlock(1900000).transactions[0]);
{
blockHash: "0x50189378a8b859a37ae92c5fb065aa1a358417bca9a051e96e1e092077ab1bd0",
blockNumber: 1900000,
from: "0x24ec54a7264311aa4bae55d0d7cf5965904eea20",
gas: 30000,
gasPrice: 20000000000,
hash: "0x88896c85c5f2b19495bda26d7646b4a55422c7373b2a7c0760009898a9d5a54f",
input: "0x",
nonce: 28,
r: "0x2983d720ad5d34086fe9d96df8e0381cf798039797b16faabfd197127c72fa14",
replayProtected: false,
s: "0x468f51648528c26b4344b69135341b556558f1a11db5813af10444cd316976e9",
to: "0x544d3a4a5f643aebd3cd4a481f6bbe970ff59a8e",
transactionIndex: 0,
v: "0x1c",
value: 13180300000000000000
}
```
__json rpc__:
```json
{
"blockHash": …
```

problem: v,r,s tx values not included in RPC Tx

---

cmd/geth/cmd.go
cmd/geth/flag.go
cmd/geth/flags.go
cmd/geth/main.go
cmd/geth/usage.go
eth/backend.go
eth/downloader/downloader.go
eth/handler.go
eth/sync.go

Added `--slow` option, that forces full sync, even if `--fast` is
specified or fast sync is in process (only fast blocks stored in DB).
This also changes the place where the "auto continuation" of fast sync
is detected/enabled.

Force full sync after starting fast sync

---

accounts/abi/bind/go.mod
accounts/abi/bind/go.sum
go.mod
go.sum

relative path replacement since the two independent go modules cannot be fixed at once with the current configuration. Node syncs with clients from eth-classic

Fixed go modules references
