ethereumproject/go-ethereum

- core/state/state_object.go
- core/state/statedb.go
Reverts ethereumproject/go-ethereum#33
> Revert "core/state: Fix memory expansion bug by not copying clean objects"

- cmd/utils/flags.go
- core/database_util.go
- core/genesis.go
- eth/backend.go
> always use latest chain config

- cmd/utils/flags.go
fix #71
example:
```
I1018 17:14:39.314252 cmd/utils/flags.go:824] --------------------------------------------------------------------------------------------------------------
I1018 17:14:39.314280 cmd/utils/flags.go:825] Starting Geth Classic 3.0.0-stable-b552d46c
I1018 17:14:39.314339 cmd/utils/flags.go:826] Loading blockchain: genesis block 0x0cd786a2425d16f152c658316c423e6ce1181e15c3295826d7c9904cba9ce303.
I1018 17:14:39.314352 cmd/utils/flags.go:827] 4 blockchain hard-forks associated with this genesis block:
I1018 17:14:39.314377 cmd/utils/flags.go:839]  Homestead hard-fork at block 494000
I1018 17:14:39.314400 cmd/utils/flags.go:839]  GasReprice hard-fork at block 1783000
I1018 17:14:39.314413 cmd/utils/flags.go:843] Geth is configured to use the Ethereum (ETC) Testnet …
```
> enable chain config banner for testnet

- cmd/utils/flags.go
TC is falling after previous commits
> fix integration tests (runs without genesis)

- cmd/geth/main.go
- cmd/utils/flags.go
> accept --oppose-dao-fork flag

- cmd/utils/flags.go
- core/config.go
- core/fork.go
> chain config for testnet

- .gitignore
Just for those who under JetBrains IDE
> .gitignore updated for IntelliJ IDEA

- cmd/utils/bootnodes.go
this is a load balancer address. mainnet is backed by cluster of 3 nodes, all working 24/7 on separate machines
> additional bootnodes

- README.md
While reading through the README I encountered the typos that have been fixed in this PR.
> fix some readme typos

- cmd/utils/customflags.go
> FIX: empty strings in flag set

- .travis.yml
- bintray.json
- cmd/geth/account.bats
- cmd/geth/genesis.bats
Amends #149 for Linux and OSX.
> Travis GitHub publication

- cmd/geth/boot.go
This PR adds 2 new seed nodes. Hopefully you can make us of them here.They are already listed on http://etcstats.net/
Keeping them online with good uptime is part of my job in a Grothendieck team.
> Add new seed nodes

- eth/backend.go
- miner/miner.go
- tests/block_test.go
Addresses _FIXME_ in documentation. Still quick and dirty.
> Use errors for unallowed gas price in miner.

- .travis.yml
> problem: travis error for bintray

- eth/downloader/downloader_test.go
solution: add 200ms pause before check
fix: #177
> problem: downloader tests fail sporadically

- common/types.go
my IDE was bothering me about it...
> Use len(Bytes) for Address and Hash .SetBytes

- core/config.go
- core/data_features.go
Just an in-progress sketch for @splix.
Haven't looked at tests or anything like that.
> Use arbitrary key-value JSON for chain feature config

- core/types/transaction.go
> problem: my IDE annoys me about these bytes

- README.md
Rel: #189 _External chain configuration, chain-specific subdirs_
Would like to merge once a release is tagged (post informal ETCDEV team beta testing?). 
PR for review of command usage modifications and configuration specifications, and to make sure my instructions are clear and correct.
**TODO:**
> README modifications documenting _Multi Chain_ milestone

- cmd/geth/chainconfig.bats
- cmd/geth/cli.bats
- cmd/geth/flag.go
- cmd/geth/genesis.bats
- cmd/geth/main.go
> --chain=morden should phase out --testnet

- README.md
- cmd/geth/chainconfig.bats
- cmd/geth/cli.bats
- cmd/geth/flag.go
- cmd/geth/genesis.bats
- core/config.go
- core/config_test.go
> '--chain=testnet' should configure testnet

- core/vm/analysis.go
> Problem: hashmap storing jumpdest results allows for exploit

- README.md
- cmd/geth/migrate_datadir.bats
Remove last case of `--chain-config` in README and fix bats test count number.
> Very minor accuracy edits

- core/config.go
- core/state_processor.go
- core/types/transaction_signing.go
- core/types/transaction_signing_test.go
- eth/handler.go
- p2p/nat/nat.go
> fix nil pointer on protected tx pubkey and relegate peer time-out log level

- CHANGELOG.md
- cmd/geth/cmd.go
- cmd/geth/flag.go
- cmd/geth/main.go
- core/blockchain.go
- core/config.go
- Also includes some minor refactoring and a sanity check for `blockchain.InsertChain`
@splix I was able to replicate and resolve your issue #274 via 53f68ba -- comparing against the current `master` branch -- but have only been able to replicate the failure once among multiple attempts.
I'm working on a further analysis to see when and how the bug was introduced (and if, and how, it's completely resolved).
> Listen for SIGTERM to stop gracefully

- internal/web3ext/web3ext.go
make method available thru js console
> include debug_accountExist function in web3 ext

- README.md
Make it clear on how to build from sources
(issue: https://github.com/ethereumproject/go-ethereum/issues/280 )
> README.md: "Download/clone the source code"

- .travis.yml
solution: move 'tags: true' to deploy field
`on: tags: true` overrides `on: branch: master`
> problem: travis deploys only on tags

- .travis.yml
- appveyor.yml
solution: skip cleanup for travis and use relative path for windows
(would like to get this deploy stuff merged and working before merging subsequent PRs)
> problem: deploy issues for appveyor and travis

- core/types/transaction.go
fix: the raw transaction signed by 'ChainIDSigner' doesn't be mined
> set the actual signer for the transaction decoded from rawtx

- .travis.yml
- deploy.sh
solution: go get it in before_deploy
> problem: travis builder for windows requires go dependency

- eth/handler.go
See https://github.com/ethereum/go-ethereum/pull/14848 for an explanation of why the line `len(headers) > 0 || !filter` is added back.
I still don't think we should check total difficulty of the peer with the fork header like ETH does. It might break light clients that only keep the last 256 blocks and does not prevent network attacks. See #313 for an explanation.
> Problem: headers is changed in FilterHeaders, so the if statement is not necessarily always true

- cmd/geth/chaincmd.go
- core/state/dump.go
It looks like better is use unsorted dumping algorithm by default
> unsorted dump is used by default now

- cmd/geth/apicmd.go
- cmd/geth/apicmd_test.go
- cmd/geth/main.go
- cmd/geth/monitorcmd.go
- console/bridge.go
- node/node_test.go
- rpc/json.go
- rpc/notification_test.go
- rpc/server_test.go
- rpc/utils.go
New CLI command (`api`) that allows executing any API method from any module.
Result is marshaled as pretty-printed JSON.
This resolves #353.
> Universal API command

- README.md
See https://github.com/ethereumproject/homebrew-classic
Resolves #361
> add instructions for installation as homebrew tap

- rpc/vendor/github.com/microsoft/go-winio/backup.go
- rpc/vendor/github.com/microsoft/go-winio/ea.go
- rpc/vendor/github.com/microsoft/go-winio/file.go
- rpc/vendor/github.com/microsoft/go-winio/fileinfo.go
- rpc/vendor/github.com/microsoft/go-winio/pipe.go
- rpc/vendor/github.com/microsoft/go-winio/zsyscall_windows.go
> rpc: update vendored microsoft/go-winio at 7843996

- README.md
Added sections about building specific tag from source and using release tarball.
> More information about building from source

- logger/glog/glog.go
solution: instead of reading symlinks from directory to find latest log
files, logger is inspected to get filenames for all severities
> problem: there are no symlinks in windows

- .travis.yml
solution: make geth binary truly static
This resolves #454.
> problem: geth with SputnikVM requires glibc-2.18

- .circleci/config.yml
> fix: cp instead of cd

- .circleci/config.yml
> problem: missing gpg dependencies

- cmd/geth/log_display_basic.go
solution: use local var of currentMode, safety check for nil on localHead calculations
> fix nil pointer in log display if currentMode changes

- README.md
- deploy.sh
* Fix for missing OS name in CircleCI.
* Status badge in README.md.
> CircleCI deployment and status

- .circleci/config.yml
- Makefile
* `gotestcov` is deprecated, replace it with script
* Fix CircleCI deploy script path
> Fix makefile and CircleCi config

- cmd/geth/cmd.go
- cmd/geth/mlog.go
- logger/mlog_file.go
Notice that this PR is to `base: pr/build-version` = #501, since they are logically connected, and rel #494
> m2/3 - mlog client start and interrupt points

- p2p/peer.go
- p2p/server.go
See https://www.cs.bu.edu/~goldbe/projects/eclipseEth.pdf Countermeasure 1.
> p2p: add DialRatio for configuration of inbound vs. dialed connections

- p2p/discover/table.go
Merge after #524.
This implements countermeasure 4 in
https://www.cs.bu.edu/~goldbe/projects/eclipseEth.pdf
>  p2p: use closest(s3) instead of closest(self) in lookup(self) 

- p2p/discover/table.go
This implements [eclipse attack](https://www.cs.bu.edu/~goldbe/projects/eclipseEth.pdf) countermeasure 5.
> p2p: always run seeding

- p2p/discover/table.go
- p2p/discover/table_test.go
- p2p/discover/udp_test.go
This implements [eclipse attack](https://www.cs.bu.edu/~goldbe/projects/eclipseEth.pdf) countermeasure 6.
> p2p: disable bonding until init is done

- .circleci/config.yml
- appveyor.yml
> CircleCI: add version check to deploy step

- README.md
> problem: Travis badge still exists in README

- cmd/geth/cmd.go
- cmd/geth/main.go
- core/atxi.go
Refactors build go routine, adds independent signal listener to build fn.
Fixes #608
> fix atxi.auto-build looping after proc interrupt

- appveyor.yml
https://github.com/ethereumproject/go-ethereum/pull/617 broke deploy key decryption because not using powershell env var syntax.
solution: use ps env var
> problem: appveyor cant decrypt file

- node/config.go
solution: refactor key file loading
Fixes #603
> problem: node key file loading fails with err=nil

- README.md
- README_Ko.md
> fix: updated links
